import the file of csv

In [1]:
import pandas as pd
house_ds = pd.read_csv("Housing.csv")

In [2]:
house_ds.head()

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   
2  12250000  9960         3          2        2      yes        no      yes   
3  12215000  7500         4          2        2      yes        no      yes   
4  11410000  7420         4          1        2      yes       yes      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished  
2              no              no        2      yes   semi-furnished  
3              no             yes        3      yes        furnished  
4              no             yes        2       no        furnished

check for the types of the col and the num of null count

In [3]:
house_ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   price             545 non-null    int64 
 1   area              545 non-null    int64 
 2   bedrooms          545 non-null    int64 
 3   bathrooms         545 non-null    int64 
 4   stories           545 non-null    int64 
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64 
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB


check if there is big variance in this col [ price / area]

In [4]:
house_ds[["price","area"]].var()

price    3.498544e+12
area     4.709512e+06
dtype: float64

import lib from sklearn which help to Encoding binary variables

In [5]:
from sklearn.preprocessing import LabelEncoder

try it on "guestroom" and covert it

In [6]:
le = LabelEncoder()
house_ds["guestroom_binary"] = le.fit_transform(house_ds["guestroom"])
print(house_ds[["guestroom_binary","guestroom"]])

     guestroom_binary guestroom
0                   0        no
1                   0        no
2                   0        no
3                   0        no
4                   1       yes
..                ...       ...
540                 0        no
541                 0        no
542                 0        no
543                 0        no
544                 0        no

[545 rows x 2 columns]


check the new col and it's type

In [7]:
house_ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   price             545 non-null    int64 
 1   area              545 non-null    int64 
 2   bedrooms          545 non-null    int64 
 3   bathrooms         545 non-null    int64 
 4   stories           545 non-null    int64 
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64 
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
 13  guestroom_binary  545 non-null    int32 
dtypes: int32(1), int64(6), object(7)
memory usage: 57.6+ KB


convert the other col

In [8]:
house_ds["mainroad_binary"] = le.fit_transform(house_ds["mainroad"])
house_ds["basement_binary"] = le.fit_transform(house_ds["basement"])
house_ds["hotwaterheating_binary"] = le.fit_transform(house_ds["hotwaterheating"])
house_ds["airconditioning_binary"] = le.fit_transform(house_ds["airconditioning"])
house_ds["prefarea_binary"] = le.fit_transform(house_ds["prefarea"])

check them

In [9]:
house_ds.head()

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   
2  12250000  9960         3          2        2      yes        no      yes   
3  12215000  7500         4          2        2      yes        no      yes   
4  11410000  7420         4          1        2      yes       yes      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  \
0              no             yes        2      yes        furnished   
1              no             yes        3       no        furnished   
2              no              no        2      yes   semi-furnished   
3              no             yes        3      yes        furnished   
4              no             yes        2       no        furnished   

   guestroom_binary  mainroad_binary  basement_binary  hotwaterheating_binary  \
0                 0                1                0                       0   
1                 0                1                0                       0   
2                 0                1                1                       0   
3                 0                1                1                       0   
4                 1                1                1                       0   

   airconditioning_binary  prefarea_binary  
0                       1                1  
1                       1                0  
2                       0                1  
3                       1                1  
4                       1                0

drop the old col

In [10]:
house_ds=house_ds.drop(["mainroad","guestroom","basement","hotwaterheating","airconditioning","prefarea"],axis=1)

In [11]:
house_ds

price  area  bedrooms  bathrooms  stories  parking furnishingstatus  \
0    13300000  7420         4          2        3        2        furnished   
1    12250000  8960         4          4        4        3        furnished   
2    12250000  9960         3          2        2        2   semi-furnished   
3    12215000  7500         4          2        2        3        furnished   
4    11410000  7420         4          1        2        2        furnished   
..        ...   ...       ...        ...      ...      ...              ...   
540   1820000  3000         2          1        1        2      unfurnished   
541   1767150  2400         3          1        1        0   semi-furnished   
542   1750000  3620         2          1        1        0      unfurnished   
543   1750000  2910         3          1        1        0        furnished   
544   1750000  3850         3          1        2        0      unfurnished   

     guestroom_binary  mainroad_binary  basement_binary  \
0                   0                1                0   
1                   0                1                0   
2                   0                1                1   
3                   0                1                1   
4                   1                1                1   
..                ...              ...              ...   
540                 0                1                1   
541                 0                0                0   
542                 0                1                0   
543                 0                0                0   
544                 0                1                0   

     hotwaterheating_binary  airconditioning_binary  prefarea_binary  
0                         0                       1                1  
1                         0                       1                0  
2                         0                       0                1  
3                         0                       1                1  
4                         0                       1                0  
..                      ...                     ...              ...  
540                       0                       0                0  
541                       0                       0                0  
542                       0                       0                0  
543                       0                       0                0  
544                       0                       0                0  

[545 rows x 13 columns]

make dummy data for " furnishingstatus " col (multi value)

In [12]:
house_ds=house_ds.join(pd.get_dummies(house_ds["furnishingstatus"],dtype=int))

drop the old one

In [13]:
house_ds=house_ds.drop("furnishingstatus",axis=1)

make the X and Y for the Model

In [14]:
y=house_ds["price"]
x=house_ds.drop("price",axis=1)

In [15]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

split the data for trainning and testing

In [16]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.25,random_state=42)
reg= LinearRegression()

fit the model

In [17]:
reg.fit(X_train,y_train)

LinearRegression()

the accurcy of the model

In [18]:
reg.score(X_test,y_test)

0.6631280462200985

In [19]:
from sklearn.model_selection import cross_val_score, KFold

In [20]:
kf = KFold(n_splits=6, shuffle=True, random_state=42)

In [21]:
cv_results = cross_val_score(reg, x, y, cv=kf)

In [22]:
cv_results

array([0.68955235, 0.61457057, 0.69030359, 0.53930511, 0.66942774,
       0.62348014])

In [23]:
import numpy as np 
np.mean(cv_results)

0.637773250789787

In [24]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
house_ds_scaled = pd.DataFrame(scaler.fit_transform(house_ds),columns=house_ds.columns)

In [25]:
house_ds_scaled.var()

price                     1.001838
area                      1.001838
bedrooms                  1.001838
bathrooms                 1.001838
stories                   1.001838
parking                   1.001838
guestroom_binary          1.001838
mainroad_binary           1.001838
basement_binary           1.001838
hotwaterheating_binary    1.001838
airconditioning_binary    1.001838
prefarea_binary           1.001838
furnished                 1.001838
semi-furnished            1.001838
unfurnished               1.001838
dtype: float64

In [26]:
y_scaled=house_ds["price"]
x_scaled=house_ds.drop("price",axis=1)
cv_results_scaled = cross_val_score(reg, x_scaled, y_scaled, cv=kf)

In [27]:
cv_results_scaled

array([0.68955235, 0.61457057, 0.69030359, 0.53930511, 0.66942774,
       0.62348014])

In [28]:
cv_results

array([0.68955235, 0.61457057, 0.69030359, 0.53930511, 0.66942774,
       0.62348014])

In [29]:
house_ds_scaled

price      area  bedrooms  bathrooms   stories   parking  \
0    4.566365  1.046726  1.403419   1.421812  1.378217  1.517692   
1    4.004484  1.757010  1.403419   5.405809  2.532024  2.679409   
2    4.004484  2.218232  0.047278   1.421812  0.224410  1.517692   
3    3.985755  1.083624  1.403419   1.421812  0.224410  2.679409   
4    3.554979  1.046726  1.403419  -0.570187  0.224410  1.517692   
..        ...       ...       ...        ...       ...       ...   
540 -1.576868 -0.991879 -1.308863  -0.570187 -0.929397  1.517692   
541 -1.605149 -1.268613  0.047278  -0.570187 -0.929397 -0.805741   
542 -1.614327 -0.705921 -1.308863  -0.570187 -0.929397 -0.805741   
543 -1.614327 -1.033389  0.047278  -0.570187 -0.929397 -0.805741   
544 -1.614327 -0.599839  0.047278  -0.570187  0.224410 -0.805741   

     guestroom_binary  mainroad_binary  basement_binary  \
0           -0.465315         0.405623        -0.734539   
1           -0.465315         0.405623        -0.734539   
2           -0.465315         0.405623         1.361397   
3           -0.465315         0.405623         1.361397   
4            2.149083         0.405623         1.361397   
..                ...              ...              ...   
540         -0.465315         0.405623         1.361397   
541         -0.465315        -2.465344        -0.734539   
542         -0.465315         0.405623        -0.734539   
543         -0.465315        -2.465344        -0.734539   
544         -0.465315         0.405623        -0.734539   

     hotwaterheating_binary  airconditioning_binary  prefarea_binary  \
0                 -0.219265                1.472618         1.804941   
1                 -0.219265                1.472618        -0.554035   
2                 -0.219265               -0.679063         1.804941   
3                 -0.219265                1.472618         1.804941   
4                 -0.219265                1.472618        -0.554035   
..                      ...                     ...              ...   
540               -0.219265               -0.679063        -0.554035   
541               -0.219265               -0.679063        -0.554035   
542               -0.219265               -0.679063        -0.554035   
543               -0.219265               -0.679063        -0.554035   
544               -0.219265               -0.679063        -0.554035   

     furnished  semi-furnished  unfurnished  
0     1.700840       -0.844888    -0.696429  
1     1.700840       -0.844888    -0.696429  
2    -0.587945        1.183588    -0.696429  
3     1.700840       -0.844888    -0.696429  
4     1.700840       -0.844888    -0.696429  
..         ...             ...          ...  
540  -0.587945       -0.844888     1.435896  
541  -0.587945        1.183588    -0.696429  
542  -0.587945       -0.844888     1.435896  
543   1.700840       -0.844888    -0.696429  
544  -0.587945       -0.844888     1.435896  

[545 rows x 15 columns]

In [30]:
from sklearn.metrics import mean_squared_error as MSE
y_pred=reg.predict(X_test)
mse_knn= MSE(y_test, y_pred)
rmse_knn = mse_knn**(1/2)
print(rmse_knn)

1245949.129409
